export const teams = [
  { name: "Buffalo Bills", abbr: "buf" },
  { name: "Miami Dolphins", abbr: "mia" },
  { name: "New England Patriots", abbr: "ne" },
  { name: "New York Jets", abbr: "nyj" },
  { name: "Baltimore Ravens", abbr: "bal" },
  { name: "Cincinnati Bengals", abbr: "cin" },
  { name: "Cleveland Browns", abbr: "cle" },
  { name: "Pittsburgh Steelers", abbr: "pit" },
  { name: "Houston Texans", abbr: "hou" },
  { name: "Indianapolis Colts", abbr: "ind" },
  { name: "Jacksonville Jaguars", abbr: "jax" },
  { name: "Tennessee Titans", abbr: "ten" },
  { name: "Denver Broncos", abbr: "den" },
  { name: "Kansas City Chiefs", abbr: "kc" },
  { name: "Las Vegas Raiders", abbr: "lv" },
  { name: "Los Angeles Chargers", abbr: "lac" },
  { name: "Dallas Cowboys", abbr: "dal" },
  { name: "New York Giants", abbr: "nyg" },
  { name: "Philadelphia Eagles", abbr: "phi" },
  { name: "Washington Football Team", abbr: "wsh" },
  { name: "Chicago Bears", abbr: "chi" },
  { name: "Detroit Lions", abbr: "det" },
  { name: "Green Bay Packers", abbr: "gb" },
  { name: "Minnesota Vikings", abbr: "min" },
  { name: "Atlanta Falcons", abbr: "atl" },
  { name: "Carolina Panthers", abbr: "car" },
  { name: "New Orleans Saints", abbr: "no" },
  { name: "Tampa Bay Buccaneers", abbr: "tb" },
  { name: "Arizona Cardinals", abbr: "ari" },
  { name: "Los Angeles Rams", abbr: "lar" },
  { name: "San Francisco 49ers", abbr: "sf" },
  { name: "Seattle Seahawks", abbr: "sea" },
];
