export const teams = [
  { name: "Buffalo Bills", espnAbbr: "buf", abbr: ["buf"] },
  { name: "Miami Dolphins", espnAbbr: "mia", abbr: ["mia"] },
  { name: "New England Patriots", espnAbbr: "ne", abbr: ["ne"] },
  { name: "New York Jets", espnAbbr: "nyj", abbr: ["nyj"] },
  { name: "Baltimore Ravens", espnAbbr: "bal", abbr: ["bal"] },
  { name: "Cincinnati Bengals", espnAbbr: "cin", abbr: ["cin"] },
  { name: "Cleveland Browns", espnAbbr: "cle", abbr: ["cle"] },
  { name: "Pittsburgh Steelers", espnAbbr: "pit", abbr: ["pit"] },
  { name: "Houston Texans", espnAbbr: "hou", abbr: ["hou"] },
  { name: "Indianapolis Colts", espnAbbr: "ind", abbr: ["ind"] },
  { name: "Jacksonville Jaguars", espnAbbr: "jax", abbr: ["jax"] },
  { name: "Tennessee Titans", espnAbbr: "ten", abbr: ["ten"] },
  { name: "Denver Broncos", espnAbbr: "den", abbr: ["den"] },
  { name: "Kansas City Chiefs", espnAbbr: "kc", abbr: ["kc"] },
  { name: "Las Vegas Raiders", espnAbbr: "lv", abbr: ["lv"] },
  { name: "Los Angeles Chargers", espnAbbr: "lac", abbr: ["lac"] },
  { name: "Dallas Cowboys", espnAbbr: "dal", abbr: ["dal"] },
  { name: "New York Giants", espnAbbr: "nyg", abbr: ["nyg"] },
  { name: "Philadelphia Eagles", espnAbbr: "phi", abbr: ["phi"] },
  {
    name: "Washington Football Team",
    espnAbbr: "wsh",
    abbr: ["wsh", "was", "wft"],
  },
  { name: "Chicago Bears", espnAbbr: "chi", abbr: ["chi"] },
  { name: "Detroit Lions", espnAbbr: "det", abbr: ["det"] },
  { name: "Green Bay Packers", espnAbbr: "gb", abbr: ["gb"] },
  { name: "Minnesota Vikings", espnAbbr: "min", abbr: ["min"] },
  { name: "Atlanta Falcons", espnAbbr: "atl", abbr: ["atl"] },
  { name: "Carolina Panthers", espnAbbr: "car", abbr: ["car"] },
  { name: "New Orleans Saints", espnAbbr: "no", abbr: ["no"] },
  { name: "Tampa Bay Buccaneers", espnAbbr: "tb", abbr: ["tb"] },
  { name: "Arizona Cardinals", espnAbbr: "ari", abbr: ["ari"] },
  { name: "Los Angeles Rams", espnAbbr: "lar", abbr: ["lar"] },
  { name: "San Francisco 49ers", espnAbbr: "sf", abbr: ["sf"] },
  { name: "Seattle Seahawks", espnAbbr: "sea", abbr: ["sea"] },
];
